xml_template = [==[
<?xml version="1.0" ?>

<!-- ************************************************** -->
<!-- * This file is automatically generated.          * -->
<!-- ************************************************** -->

<!-- Experiment number: %experiment-number% 				-->
<!-- Arena size:        %arena-size% 				-->
<!-- Experiment length: %experiment-length% 				-->
<!-- Number of robots:  %number-of-robots% 				-->
<!-- Output files:      %trace-output% 	-->
<!--                    %collision-output% 	-->
<!--                    %summary-output% 	-->

<argos-configuration>

  <!-- ************************* -->
  <!-- * General configuration * -->
  <!-- ************************* -->
  <framework>
    <system threads="0" />
    <experiment length="%experiment-length%"
                ticks_per_second="10"
                random_seed="%random-seed%" />
  </framework>

  <!-- *************** -->
  <!-- * Controllers * -->
  <!-- *************** -->
  <controllers>

    <footbot_foraging_controller id="ffc"
                                 library="build/controllers/footbot_foraging/%foraging-controller%">
      <actuators>
        <footbot_wheels implementation="default" />
        <footbot_leds implementation="default" />
        <range_and_bearing implementation="default" range="1" />
      </actuators>
      <sensors>
        <footbot_proximity implementation="rot_z_only" show_rays="false" calibrate="true" />
        <footbot_light implementation="rot_z_only" show_rays="false" calibrate="true" />
        <footbot_motor_ground implementation="rot_z_only" calibrate="true" />
        <range_and_bearing implementation="default" />
      </sensors>
      <parameters>
        <diffusion go_straight_angle_range="-5:5"
                   delta="0.1" />
        <wheel_turning hard_turn_angle_threshold="90"
                       soft_turn_angle_threshold="70"
                       no_turn_angle_threshold="10"
                       max_speed="10" />
        <state rest_to_explore_mean="20"
               minimum_resting_time="1"
               minimum_search_for_place_in_nest_time="50">
	</state>
      </parameters>
    </footbot_foraging_controller>

  </controllers>

  <!-- ****************** -->
  <!-- * Loop functions * -->
  <!-- ****************** -->
  <loop_functions library="build/loop_functions/foraging_loop_functions/%user-function%"
                  label="foraging_loop_functions">
    <foraging items="15"
              radius="0.1"
	      food_drop_mean="100"
              energy_per_item="1000"
              energy_per_walking_robot="1"
              trace_output="%trace-output%"
	      collision_output="%collision-output%"
	      id_for_collision_output="%id-for-collision-output%"
	      summary_output="%summary-output%"/>
  </loop_functions>

  <!-- *********************** -->
  <!-- * Arena configuration * -->
  <!-- *********************** -->
  <arena size="4, 4, 1">

    <floor id="floor"
           source="loop_functions"
           pixels_per_meter="50" />

    <box id="wall_north"
         position="%wall-north-position%"
         orientation="0,0,0"
         size="%wall-north-size%"
         movable="false" />
    <box id="wall_south"
         position="%wall-south-position%"
         orientation="0,0,0"
         size="%wall-south-size%"
         movable="false" />
    <box id="wall_east"
         position="%wall-east-position%"
         orientation="0,0,0"
         size="%wall-east-size%"
         movable="false" />
    <box id="wall_west"
         position="%wall-west-position%"
         orientation="0,0,0"
         size="%wall-west-size%"
         movable="false" />

    <light id="light_1"
           position="%light-1-position%"
           orientation="0,0,0"
           color="yellow"
           intensity="3.0" />
    <light id="light_2"
           position="%light-2-position%"
           orientation="0,0,0"
           color="yellow"
           intensity="3.0" />
    <light id="light_3"
           position="%light-3-position%"
           orientation="0,0,0"
           color="yellow"
           intensity="3.0" />
    <light id="light_4"
           position="%light-4-position%"
           orientation="0,0,0"
           color="yellow"
           intensity="3.0" />

    <distribute>
      <position method="uniform" min="%position-min%" max="%position-max%" />
      <orientation method="uniform" min="%orientation-min%" max="%orientation-max%" />
      <entity quantity="%number-of-robots%" max_trials="100">
        <foot-bot id="fb"
                  controller="ffc" />
      </entity>
    </distribute>

  </arena>

  <!-- ******************* -->
  <!-- * Physics engines * -->
  <!-- ******************* -->
  <physics_engines>
    <dynamics2d id="dyn2d" />
  </physics_engines>

  <!-- ************************************ -->
  <!-- * Arena -> Physics Engines mapping * -->
  <!-- ************************************ -->
  <arena_physics>
    <engine id="dyn2d">
      <!--
         You can use a regular expression to bind a set of entities.
         See 'man 3 regex' to know more about regular expressions.
        -->
      <entity id="fb_[[:digit:]]*" />
      <entity id="wall_north" />
      <entity id="wall_south" />
      <entity id="wall_east" />
      <entity id="wall_west" />
    </engine>
  </arena_physics>

  <!-- ****************** -->
  <!-- * Visualization * -->
  <!-- ****************** -->
  <visualization>
  </visualization>

</argos-configuration>
]==]
